CREATE VIEW PARTSELL
AS
SELECT
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY,
    (
        SELECT
            COUNT(*)
        FROM LINEITEM
        WHERE LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
    ) AS SELL_COUNT,
    (
        SELECT
            SUM(L_PROFIT)
        FROM
            LINEITEM
        WHERE LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
    ) AS TOTAL_PROFIT
FROM
    PARTSUPP;

GO
SELECT
    PS_SUPPKEY,
    SUM(SELL_COUNT) AS SUPP_SELL_COUNT,
    SUM(TOTAL_PROFIT) AS SUPP_TOTAL_PROFIT
INTO SUPP_SELL
FROM
    PARTSELL
GROUP BY PS_SUPPKEY
--ORDER BY SUPP_TOTAL_PROFIT DESC;

SELECT
    PS_PARTKEY,
    SUM(SELL_COUNT) AS PART_SELL_COUNT,
    SUM(TOTAL_PROFIT) AS PART_TOTAL_PROFIT
INTO PART_SELL
FROM
    PARTSELL
GROUP BY PS_PARTKEY
--ORDER BY PART_TOTAL_PROFIT DESC;
