CREATE VIEW PARTSELL
AS
SELECT
    PARTSUPP.PS_PARTKEY,
    PARTSUPP.PS_SUPPKEY,
    (
        SELECT
            COUNT(*)
        FROM LINEITEM
        WHERE LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
    ) AS SELL_COUNT,
    (
        SELECT
            SUM(L_PROFIT)
        FROM
            LINEITEM
        WHERE LINEITEM.L_PARTKEY = PARTSUPP.PS_PARTKEY AND LINEITEM.L_SUPPKEY = PARTSUPP.PS_SUPPKEY
    ) AS TOTAL_PROFIT
FROM
    PARTSUPP;

GO
SELECT
    PS_SUPPKEY,
    SUM(SELL_COUNT) AS SUPP_SELL_COUNT,
    SUM(TOTAL_PROFIT) AS SUPP_TOTAL_PROFIT
INTO SUPP_SELL
FROM
    PARTSELL
GROUP BY PS_SUPPKEY
--ORDER BY SUPP_TOTAL_PROFIT DESC;

SELECT
    PS_PARTKEY,
    SUM(SELL_COUNT) AS PART_SELL_COUNT,
    SUM(TOTAL_PROFIT) AS PART_TOTAL_PROFIT
INTO PART_SELL
FROM
    PARTSELL
GROUP BY PS_PARTKEY
--ORDER BY PART_TOTAL_PROFIT DESC;


SELECT
    PS_SUPPKEY,
    COUNT(PS_PARTKEY)
FROM PARTSUPP
GROUP BY PS_SUPPKEY;


SELECT
    PS_SUPPKEY,
    COUNT(PS_PARTKEY) AS KIND,
    SUM(SELL_COUNT) AS PART_SELL_COUNT,
    SUM(TOTAL_PROFIT) AS PART_TOTAL_PROFIT
INTO SUPPRANK
FROM PARTSELL
GROUP BY PS_SUPPKEY;

CREATE TABLE RANK_TEMP
(
    PS_SUPPKEY INTEGER PRIMARY KEY,
    KIND INTEGER,
    PART_SELL_COUNT INTEGER,
    PART_TOTAL_PROFIT INTEGER,
    RANK FLOAT
);

BULK INSERT RANK_TEMP
FROM 'D:\Programs\Term 3 - SQL Business\Homework 03 - Final Work\Data\supp_rank.csv'
with
(
    fieldterminator=',',
    firstrow=2,
    rowterminator='\n'
);
