-- 添加时间分类以供 Power BI 创建时间维度分析

-- Order_orderDate
SELECT
    ORDERS.O_ORDERKEY,
    ORDERS.O_ORDERDATE,
    year(ORDERS.O_ORDERDATE) AS O_YEAR,
    month(ORDERS.O_ORDERDATE) AS O_MONTH,
    day(ORDERS.O_ORDERDATE) AS O_DAY
INTO
    O_ORDERDATE_TABLE
FROM ORDERS;

ALTER TABLE ORDERS ADD O_YEAR INTEGER;
ALTER TABLE ORDERS ADD O_MONTH INTEGER;
ALTER TABLE ORDERS ADD O_DAY INTEGER;

UPDATE ORDERS SET O_YEAR = YEAR(O_ORDERDATE);
UPDATE ORDERS SET O_MONTH = MONTH(O_ORDERDATE);
UPDATE ORDERS SET O_DAY = DAY(O_ORDERDATE);

-- LineItem_shipDate
SELECT
    LINEITEM.L_ORDERKEY,
    LINEITEM.L_LINENUMBER,
    LINEITEM.L_SHIPDATE,
    year(LINEITEM.L_SHIPDATE) AS L_SHIPDATE_YEAR,
    month(LINEITEM.L_SHIPDATE) AS L_SHIPDATE_MONTH,
    day(LINEITEM.L_SHIPDATE) AS L_SHIPDATE_DAY
INTO
    L_SHIPDATE_TABLE
FROM LINEITEM;

-- LineItem_commitDate
SELECT
    LINEITEM.L_ORDERKEY,
    LINEITEM.L_LINENUMBER,
    LINEITEM.L_COMMITDATE,
    year(LINEITEM.L_COMMITDATE) AS L_COMMITDATE_YEAR,
    month(LINEITEM.L_COMMITDATE) AS L_COMMITDATE_MONTH,
    day(LINEITEM.L_COMMITDATE) AS L_COMMITDATE_DAY
INTO
    L_COMMITDATE_TABLE
FROM LINEITEM;

-- LineItem_receipDate
SELECT
    LINEITEM.L_ORDERKEY,
    LINEITEM.L_LINENUMBER,
    LINEITEM.L_RECEIPTDATE,
    year(LINEITEM.L_RECEIPTDATE) AS L_RECEIPTDATE_YEAR,
    month(LINEITEM.L_RECEIPTDATE) AS L_RECEIPTDATE_MONTH,
    day(LINEITEM.L_RECEIPTDATE) AS L_RECEIPTDATE_DAY
INTO
    L_RECEIPTDATE_TABLE
FROM LINEITEM;
